### ISSUE TITLE
The program getting stuck

### ISSUE THREAD

**Issue by VenomRaiden** [Vinyzu/DiscordGenerator#19]
If u use for than one thread without any proxies some times the captchas gets solved together and only one of the browser is able to make a account and for the others there is a error message your are being rate limited. For some reason when this happens the programs just stops and does nothing.
I can it could be because there is no error for this and it would be great if u can add a error or a cooldown (Like after the captcha is done a cooldown starts and when the time is up its just closes the browser and start again) for this.

**Comment by Vinyzu** [comment]
You have to use proxies to generate multiple accounts at once.
The browser should close after 20 seconds of rate limit.
Basicly it waits 20 seconds if it doesnt find a captcha until then it closes. The timeout is that high because many people who are using slow proxies reported to me that the timeout was to low

**Comment by VenomRaiden** [comment]
> You have to use proxies to generate multiple accounts at once. The browser should close after 20 seconds of rate limit. Basicly it waits 20 seconds if it doesnt find a captcha until then it closes. The timeout is that high because many people who are using slow proxies reported to me that the timeout was to low

ok i understand
